2022-08-14 11:01:13:113 - [31merror[39m: [31mN√£o foi poss√≠vel conectar ao banco de dados![39m
2022-08-14 11:01:13:113 - [31merror[39m: [31mErro: MongoServerError: bad auth : Authentication failed.[39m
2022-08-14 13:06:20:620 - [31merror[39m: [31mErro no sistema: Cast to ObjectId failed for value "62f91b44b6e0eb0485410c1" (type string) at path "_id" for model "Movie"[39m
2022-08-14 13:20:03:203 - [31merror[39m: [31mErro no sistema: Cast to ObjectId failed for value "62f91555b763ff12a7520fd66" (type string) at path "_id" for model "Movie"[39m
2022-08-14 13:28:04:284 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:30:24:3024 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:30:37:3037 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:32:32:3232 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:33:34:3334 - [31merror[39m: [31mErro no sistema: Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:34:04:344 - [31merror[39m: [31mErro no sistema: Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:35:15:3515 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
2022-08-14 13:36:01:361 - [31merror[39m: [31mErro no sistema: Performing an update on the path '_id' would modify the immutable field '_id'[39m
